app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#prefix => variable d'url avec la locale, variable existant de base dans symfony => entre {} , c'est une variable
    prefix: /{_locale}
    requirements:
        _locale: "fr|en|es"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth-connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /oauth-connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /oauth-login

google_login:
    path: /oauth-login/check-google
