# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.services.handler:
        class: AppBundle\Service\Handler\FormHandler
        arguments: [ '@doctrine','@app.services.utils.string' ]
    app.services.moviehandler:
        class: AppBundle\Service\Handler\MovieHandler
        arguments: [ '@doctrine','@app.services.utils.string', '@app.services.utils.upload' ]

    app.services.userhandler:
            class: AppBundle\Service\Handler\UserHandler
            arguments: [ '@doctrine','@security.password_encoder' ]



    app.services.utils.upload:
        class: AppBundle\Service\Utils\UploadUtils
        arguments: [ '@app.services.utils.string', '%upload_dir%' ]

    app.services.utils.string:
            class: AppBundle\Service\Utils\StringUtils
            arguments: [ ]

    app.form.search:
        class: AppBundle\Form\MovieSearchType
        arguments: [ '@doctrine' ]
        tags:
            - { name: form.type}

#    app.form.movierepository:
#       class: AppBundle\Repository\MovieRepository
        #factory: ["@doctrine", getRepository]
#        arguments: [ "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Movie')", '%pagination_max%']


    #app.form.movierepository:
    #    class: AppBundle\Repository\MovieRepository
    #    \Doctrine\ORM\Mapping\ClassMetadata
    #    arguments: [ '@doctrine.orm.default_entity_manager','@met','%pagination_max%' ]


    app.serializer.normalizer.object:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        tags:
            - { name: serializer.normalizer }

    app.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        tags:
            - { name: serializer.encoder }

    app.serializer.encoder.xml:
        class: Symfony\Component\Serializer\Encoder\XmlEncoder
        tags:
            - { name: serializer.encoder }

    app.serializer:
        class: AppBundle\Service\Serializer\AppSerializer
        arguments: [ '@app.serializer.normalizer.object', ['@app.serializer.encoder.json', '@app.serializer.encoder.xml'] ]



    app.services.listener.category:
        class: AppBundle\Service\Listener\CategoryListener
        arguments:  [ '@app.services.utils.string' ]
        tags:
            - { name: doctrine.orm.entity_listener }
    app.services.listener.movie:
        class: AppBundle\Service\Listener\MovieListener
        arguments:  [ '@app.services.utils.string' , '%upload_dir%' ]
        tags:
            - { name: doctrine.orm.entity_listener }
    app.services.listener.actor:
        class: AppBundle\Service\Listener\ActorListener
        arguments:  [ '@app.services.utils.string' , '%upload_dir%' ]
        tags:
            - { name: doctrine.orm.entity_listener }
    app.services.subscriber.movieform:
        class: AppBundle\Service\Subscriber\MovieFormSubscriber
        arguments:  [  ]
        tags:
            - { name: kernel.event_subscriber }
    app.services.subscriber.kernelevents:
        class: AppBundle\Service\Subscriber\KernelEventsSubscriber
        arguments:  [ '@twig' ]
        tags:
            - { name: kernel.event_subscriber }

    app.services.subscriber.authentification:
                    class: AppBundle\Service\Subscriber\AuthentificationSubscriber
                    arguments:  [ '@doctrine', '@session', '@mailer', '%max_authentification_failure%' ]
                    tags:
                        - { name: kernel.event_subscriber }

    app.services.suscriber.orderevents:
        class: AppBundle\Service\Subscriber\OrderEventsSubscriber
        arguments: [ '@knp_snappy.pdf', '@twig' , '@app.services.basket', '@doctrine' ]
        tags:
            - { name: kernel.event_subscriber }

    app.services.twig:
        class: AppBundle\Service\Twig\FunctionExtension
        arguments: [ '@twig','@request_stack','@router','@session','@doctrine','@app.services.basket','%locales%' ]
        tags:
            - { name: twig.extension }

    app.services.basket:
        class: AppBundle\Service\Basket\Basket
        arguments: [ '@session','@doctrine' ]
